name: Tests

on:
  push:
    branches: [ main, develop, next ]
  pull_request:
    branches: [ main, develop, next ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [ 8.1, 8.2, 8.3, 8.4 ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          tools: composer:v2
          coverage: none
          ini-values: error_reporting=E_ALL, zend.assertions=1

      - name: Install dependencies
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --prefer-dist --no-interaction --no-progress

      - name: Execute architectural layers static analysis
        run: composer run deptrac

      - name: Execute code static analysis
        run: composer run static

      - name: Execute style
        run: composer run style -- --bail

      - name: Execute tests
        run: composer run test
